CREATE DATABASE IF NOT EXISTS `THEATERSHOWS`;
USE `THEATERSHOWS`;

CREATE TABLE `payment` (
  `PAYMENT_ID` INT AUTO_INCREMENT,
  `AMOUNT` DECIMAL,
  `STATUS` VARCHAR(50),
  `PAYMENT_DATE` DATE,
  PRIMARY KEY (`PAYMENT_ID`)
);

CREATE TABLE `customers` (
  `CUSTOMER_ID` INT AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(50),
  `LAST_NAME` VARCHAR(50),
  `PHONE_NUMBER` VARCHAR(50),
  `EMAIL_ADDRESS` VARCHAR(50),
  PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE `theaters` (
  `THEATER_ID` INT AUTO_INCREMENT,
  `CAPACITY` INT,
  `LAYOUT` VARCHAR(50),
  `STATUS` VARCHAR(50),
  `AVAILABLE_DATE` DATE,
  `AVAILABLE_TIME` TIME,
  PRIMARY KEY (`THEATER_ID`)
);

CREATE TABLE `shows` (
  `SHOW_ID` VARCHAR(50) UNIQUE,
  `TITLE` VARCHAR(50),
  `RUNTIME` TIME,
  `SHOW_PRICE` DECIMAL,
  `STATUS` VARCHAR(50),
  PRIMARY KEY (`SHOW_ID`)
);

CREATE TABLE `theater_shows` (
  `THEATER_SHOW_ID` INT AUTO_INCREMENT,
  `THEATER_ID` INT,
  `SHOW_ID` VARCHAR(50),
  `START_TIME` TIME,
  `END_TIME` TIME,
  `SHOW_STATUS` VARCHAR(50),
  `AUDIENCE_TURNOUT` INT,
  PRIMARY KEY (`THEATER_SHOW_ID`),
  FOREIGN KEY (`THEATER_ID`)
      REFERENCES `theaters`(`THEATER_ID`),
  FOREIGN KEY (`SHOW_ID`)
      REFERENCES `shows`(`SHOW_ID`)
);

CREATE TABLE `booking` (
  `BOOKING_ID` INT AUTO_INCREMENT,
  `CUSTOMER_ID` INT,
  `THEATER_SHOW_ID` INT,
  `PAYMENT_ID` INT UNIQUE,
  `NOOFTICKETS` INT,
  `TOTAL_PRICE` DECIMAL,
  `STATUS` VARCHAR(50),
  `BOOKING_DATE` DATE,
  PRIMARY KEY (`BOOKING_ID`),
  FOREIGN KEY (`CUSTOMER_ID`)
      REFERENCES `customers`(`CUSTOMER_ID`),
  FOREIGN KEY (`PAYMENT_ID`)
      REFERENCES `payment`(`PAYMENT_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`THEATER_SHOW_ID`)
      REFERENCES `theater_shows`(`THEATER_SHOW_ID`)
);

CREATE TABLE `seat` (
  `SEAT_ID` INT,
  `THEATER_ID` INT,
  `ROW_NO` INT,
  `COL_NO` INT,
  `STATUS` VARCHAR(50),
  PRIMARY KEY (`SEAT_ID`),
  FOREIGN KEY (`THEATER_ID`)
      REFERENCES `theaters`(`THEATER_ID`)
);

CREATE TABLE `seat_booking` (
  `BOOKING_ID` INT,
  `SEAT_ID` INT,
  PRIMARY KEY (`BOOKING_ID`, `SEAT_ID`),
  FOREIGN KEY (`BOOKING_ID`)
      REFERENCES `booking`(`BOOKING_ID`),
  FOREIGN KEY (`SEAT_ID`)
      REFERENCES `seat`(`SEAT_ID`)
);

CREATE TABLE `staff` (
  `STAFF_ID` INT AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(50),
  `LAST_NAME` VARCHAR(50),
  `POSITION` VARCHAR(50),
  `STATUS` VARCHAR(50),
  `SHIFT` VARCHAR(50),
  `SALARY` DECIMAL,
  PRIMARY KEY (`STAFF_ID`)
);

CREATE TABLE `staff_assignment` (
  `STAFF_ID` INT,
  `SHOW_ID` VARCHAR(50),
  `ASSIGNMENT_DATE` DATE,
  `START_TIME` TIME,
  `END_TIME` TIME,
  PRIMARY KEY (`STAFF_ID`, `SHOW_ID`),
  FOREIGN KEY (`SHOW_ID`)
      REFERENCES `shows`(`SHOW_ID`),
  FOREIGN KEY (`STAFF_ID`)
      REFERENCES `staff`(`STAFF_ID`)
);