/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*; 
import java.util.logging.*;
import java.sql.*;

import dao.SQLConnect;

/**
 *
 * @author ToIuMonoRyōshi
 */
public class App extends JFrame {

    private static final Logger logger = Logger.getLogger(App.class.getName());

    /**
     * Creates new form App
     */
    public App() {
        //setSize(getPreferredSize());
        //setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new JPanel();
        title = new JLabel();
        GroupNo = new JLabel();
        sidebar = new JPanel();
        reports = new JLabel();
        showRecords = new JButton();
        theaterRecords = new JButton();
        staffRecords = new JButton();
        customerRecords = new JButton();
        records = new JLabel();
        bookTickets = new JButton();
        cancelBookings = new JButton();
        staffAssignments = new JButton();
        scheduleShows = new JButton();
        payments = new JButton();
        transaction1 = new JLabel();
        bookingStatus = new JButton();
        theaterPerformance = new JButton();
        financialPerformance = new JButton();
        staffAssignment = new JButton();
        buttonPanel = new JPanel();
        dashboard = new JLabel();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1366, 768));

        header.setBackground(new Color(102, 204, 0));

        title.setFont(new Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Hotel Theater Shows Database");

        GroupNo.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        GroupNo.setForeground(new Color(102, 102, 102));
        GroupNo.setText("Group 8");

        GroupLayout headerLayout = new GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(headerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(GroupNo)
                    .addComponent(title))
                .addContainerGap(630, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GroupNo)
                .addContainerGap())
        );

        sidebar.setBackground(new Color(51, 153, 0));

        reports.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        reports.setText("Generate Reports");

        showRecords.setText("Show");
        showRecords.addActionListener(this::showRecordsActionPerformed);

        theaterRecords.setText("Theater");
        theaterRecords.addActionListener(this::theaterRecordsActionPerformed);

        staffRecords.setText("Staff");
        staffRecords.addActionListener(this::staffRecordsActionPerformed);

        customerRecords.setText("Customer");
        customerRecords.addActionListener(this::customerRecordsActionPerformed);

        records.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        records.setText("Manage Records");

        bookTickets.setText("Book Show Tickets");
        bookTickets.addActionListener(this::bookTicketsActionPerformed);

        cancelBookings.setText("Cancel Bookings");
        cancelBookings.addActionListener(this::cancelBookingsActionPerformed);

        staffAssignments.setText("Staff Assignments");
        staffAssignments.addActionListener(this::staffAssignmentsActionPerformed);

        scheduleShows.setText("Schedule Shows");
        scheduleShows.addActionListener(this::scheduleShowsActionPerformed);

        payments.setText("Payments");
        payments.addActionListener(this::paymentsActionPerformed);

        transaction1.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        transaction1.setText("Make Transaction");

        bookingStatus.setText("Booking Status");
        bookingStatus.addActionListener(this::bookingStatusActionPerformed);

        theaterPerformance.setText("Theater Performance");
        theaterPerformance.addActionListener(this::theaterPerformanceActionPerformed);

        financialPerformance.setText("Financial Performance");
        financialPerformance.addActionListener(this::financialPerformanceActionPerformed);

        staffAssignment.setText("Staff Assignment");
        staffAssignment.addActionListener(this::staffAssignmentActionPerformed);

        GroupLayout sidebarLayout = new GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(sidebarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(theaterRecords, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(showRecords, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffRecords, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerRecords, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookTickets, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBookings, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffAssignments, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(scheduleShows, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(payments, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingStatus, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(theaterPerformance, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(financialPerformance, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)
                            .addComponent(staffAssignment, GroupLayout.PREFERRED_SIZE, 216, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(reports))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(records))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(transaction1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(records)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showRecords)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theaterRecords)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffRecords)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerRecords)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaction1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookTickets)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBookings)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAssignments)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scheduleShows)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payments)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reports)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingStatus)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theaterPerformance)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(financialPerformance)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAssignment)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanel.setBackground(new Color(204, 204, 204));
        buttonPanel.setLayout(new GridLayout(0, 2, 2, 10));

        dashboard.setFont(new Font("Segoe UI", 0, 36)); // NOI18N
        dashboard.setText("Welcome to Dashboard, click any button to get started");
        buttonPanel.add(dashboard);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sidebar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(header, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidebar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingStatusActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bookingStatusActionPerformed
        // TODO add your handling code here:
        com.Reports.BookingReports.generateReport();
        resetDashboard();
    }//GEN-LAST:event_bookingStatusActionPerformed

    private void theaterPerformanceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_theaterPerformanceActionPerformed
        // TODO add your handling code here:
        com.Reports.TheaterPerformanceReport.generateReport();
        resetDashboard();
    }//GEN-LAST:event_theaterPerformanceActionPerformed

    private void financialPerformanceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_financialPerformanceActionPerformed
        // TODO add your handling code here:
        com.Reports.FinanicalPerformanceReport.generateReport();
        resetDashboard();
    }//GEN-LAST:event_financialPerformanceActionPerformed

    private void staffAssignmentActionPerformed(ActionEvent evt) {//GEN-FIRST:event_staffAssignmentActionPerformed
        // TODO add your handling code here:
        com.Reports.StaffAssignmentReport.generateReport();
        resetDashboard();
    }//GEN-LAST:event_staffAssignmentActionPerformed

    private void showRecordsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_showRecordsActionPerformed
        // TODO add your handling code here:
        JButton addShow = new JButton("Add New Show");
        JButton updateShow = new JButton("Update Show Details");
        JButton deleteShow = new JButton("Delete Show");
        JButton viewAllShows = new JButton("View All Shows");
        JButton viewShowDetails = new JButton("View Show Details");
        JButton listAllUpcomingShows = new JButton("List All Upcoming Shows");

        addShow.addActionListener(e -> {
            com.Records.ShowRecords.enterShowDetails();
            resetDashboard();
        });
        updateShow.addActionListener(e -> {
            com.Records.ShowRecords.updateShowDetails();
            resetDashboard();
        });
        deleteShow.addActionListener(e -> {
            com.Records.ShowRecords.deleteShow();
            resetDashboard();
        });
        viewAllShows.addActionListener(e -> {
            com.Records.ShowRecords.viewAllShows();
            resetDashboard();
        });
        viewShowDetails.addActionListener(e -> {
            com.Records.ShowRecords.viewShowDetails();
            resetDashboard();
        });
        listAllUpcomingShows.addActionListener(e -> {
            com.Records.ShowRecords.viewUpcomingShows();
            resetDashboard();
        });

        buttonPanel.removeAll();
        buttonPanel.add(addShow);
        buttonPanel.add(updateShow);
        buttonPanel.add(deleteShow);
        buttonPanel.add(viewAllShows);
        buttonPanel.add(viewShowDetails);
        buttonPanel.add(listAllUpcomingShows);
        buttonPanel.revalidate();
        buttonPanel.repaint();
    }//GEN-LAST:event_showRecordsActionPerformed

    private void theaterRecordsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_theaterRecordsActionPerformed
        // TODO add your handling code here:
        JButton addTheater = new JButton("Add New Theater");
        JButton updateTheater = new JButton("Update Theater Details");
        JButton deleteTheater = new JButton("Delete Theater Record");
        JButton viewTheaterStatus = new JButton("View Theater Record by Status");
        JButton listAllActiveTheaters = new JButton("List All Active Theaters");
        JButton listAllTheaters = new JButton("List All Theaters");
        JButton viewTheaterUsedbyShow = new JButton("View Theaters Used by Show");

        addTheater.addActionListener(e -> {
            com.Records.TheaterRecords.addTheaterRecord();
            resetDashboard();
        });
        updateTheater.addActionListener(e -> {
            com.Records.TheaterRecords.updateTheaterRecord();
            resetDashboard();
        });
        deleteTheater.addActionListener(e -> {
            com.Records.TheaterRecords.deleteTheaterRecord();
            resetDashboard();
        });
        viewTheaterStatus.addActionListener(e -> {
            com.Records.TheaterRecords.viewTheaterRecordByStatus();
            resetDashboard();
        });
        listAllActiveTheaters.addActionListener(e -> {
            com.Records.TheaterRecords.listAllActiveTheaters();
            resetDashboard();
        });
        listAllTheaters.addActionListener(e -> {
            com.Records.TheaterRecords.listAllTheaters();
            resetDashboard();
        });
        viewTheaterUsedbyShow.addActionListener(e -> {
            com.Records.TheaterRecords.viewTheaterUsedByShow();
            resetDashboard();
        });

        buttonPanel.removeAll();
        buttonPanel.add(addTheater);
        buttonPanel.add(updateTheater);
        buttonPanel.add(deleteTheater);
        buttonPanel.add(viewTheaterStatus);
        buttonPanel.add(listAllActiveTheaters);
        buttonPanel.add(listAllTheaters);
        buttonPanel.add(viewTheaterUsedbyShow);
        buttonPanel.revalidate();
        buttonPanel.repaint();
    }//GEN-LAST:event_theaterRecordsActionPerformed

    private void staffRecordsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_staffRecordsActionPerformed
        // TODO add your handling code here:
        JButton addStaff = new JButton("Add New Staff");
        JButton updateStaff = new JButton("Update Staff Details");
        JButton deleteStaff = new JButton("Delete Staff Record");
        JButton viewStaffByPos = new JButton("View Staff by Position");
        JButton viewStaffByEmp = new JButton("View Staff by Employment Status");
        JButton viewStaffSalary = new JButton("View All Staff Salaries");
        JButton listAllStaff = new JButton("List All Staff Members");
        JButton viewStaffwShows = new JButton("View Staff with Show Details");
        JButton viewAllStaffFrShow = new JButton("View All Staff for a Specific Show");

        addStaff.addActionListener(e -> {
            com.Records.StaffRecords.enterStaffDetails();
            resetDashboard();
        });
        updateStaff.addActionListener(e -> {
            com.Records.StaffRecords.updateStaffDetails();
            resetDashboard();
        });
        deleteStaff.addActionListener(e -> {
            com.Records.StaffRecords.deleteStaff();
            resetDashboard();
        });
        viewStaffByPos.addActionListener(e -> {
            com.Records.StaffRecords.viewStaffByPosition();
            resetDashboard();
        });
        viewStaffByEmp.addActionListener(e -> {
            com.Records.StaffRecords.viewStaffByShift();
            resetDashboard();
        });
        viewStaffSalary.addActionListener(e -> {
            com.Records.StaffRecords.viewAllStaffSalaries();
            resetDashboard();
        });
        listAllStaff.addActionListener(e -> {
            com.Records.StaffRecords.listAllStaff();
            resetDashboard();
        });
        viewStaffwShows.addActionListener(e -> {
            com.Records.StaffRecords.viewStaffWithShowDetails();
            resetDashboard();
        });
        viewAllStaffFrShow.addActionListener(e -> {
            com.Records.StaffRecords.viewStaffForShow();
            resetDashboard();
        });

        buttonPanel.removeAll();
        buttonPanel.add(addStaff);
        buttonPanel.add(updateStaff);
        buttonPanel.add(deleteStaff);
        buttonPanel.add(viewStaffByPos);
        buttonPanel.add(viewStaffByEmp);
        buttonPanel.add(viewStaffSalary);
        buttonPanel.add(listAllStaff);
        buttonPanel.add(viewStaffwShows);
        buttonPanel.add(viewAllStaffFrShow);
        buttonPanel.revalidate();
        buttonPanel.repaint();
    }//GEN-LAST:event_staffRecordsActionPerformed

    private void customerRecordsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_customerRecordsActionPerformed
        // TODO add your handling code here:
        JButton addCus = new JButton("Add Customer Details");
        JButton updateCus = new JButton("Update Customer Details");
        JButton deleteCus = new JButton("Delete a Customer");
        JButton viewCusA = new JButton("View All Customers by last name alphabetically");
        JButton listCusFNames = new JButton("List all customer full names");
        JButton listCus = new JButton("List all customer details");
        JButton viewCusWB = new JButton("View Customers with booking details");

        addCus.addActionListener(e -> {
            com.Records.CustomerRecords.AddCustomer();
            resetDashboard();
        });
        updateCus.addActionListener(e -> {
            com.Records.CustomerRecords.updateCustomer();
            resetDashboard();
        });
        deleteCus.addActionListener(e -> {
            com.Records.CustomerRecords.deleteCustomer();
            resetDashboard();
        });
        viewCusA.addActionListener(e -> {
            com.Records.CustomerRecords.viewCustomerByLName();
            resetDashboard();
        });
        listCusFNames.addActionListener(e -> {
            com.Records.CustomerRecords.listAllCustomerNames();
            resetDashboard();
        });
        listCus.addActionListener(e -> {
            com.Records.CustomerRecords.listAllCustomers();
            resetDashboard();
        });
        viewCusWB.addActionListener(e -> {
            com.Records.CustomerRecords.viewCustomerBooking();
            resetDashboard();
        });

        buttonPanel.removeAll();
        buttonPanel.add(addCus);
        buttonPanel.add(updateCus);
        buttonPanel.add(deleteCus);
        buttonPanel.add(viewCusA);
        buttonPanel.add(listCusFNames);
        buttonPanel.add(listCus);
        buttonPanel.add(viewCusWB);
        buttonPanel.revalidate();
        buttonPanel.repaint();
    }//GEN-LAST:event_customerRecordsActionPerformed

    private void bookTicketsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bookTicketsActionPerformed
        // TODO add your handling code here:
        com.Transactions.Booking.bookShowTickets();
        resetDashboard();
    }//GEN-LAST:event_bookTicketsActionPerformed

    private void cancelBookingsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelBookingsActionPerformed
        // TODO add your handling code here:
        com.Transactions.Booking.cancelBooking();
        resetDashboard();
    }//GEN-LAST:event_cancelBookingsActionPerformed

    private void staffAssignmentsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_staffAssignmentsActionPerformed
        // TODO add your handling code here:
        com.Transactions.StaffAssignment.assignStaff();
        resetDashboard();
    }//GEN-LAST:event_staffAssignmentsActionPerformed

    private void scheduleShowsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_scheduleShowsActionPerformed
        // TODO add your handling code here:
        com.Transactions.Booking.addNewTheaterShow();
        resetDashboard();
    }//GEN-LAST:event_scheduleShowsActionPerformed

    private void paymentsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_paymentsActionPerformed
        // TODO add your handling code here:
        com.Transactions.Booking.pay();
        resetDashboard();
    }//GEN-LAST:event_paymentsActionPerformed

    
    public void resetDashboard() {
        // put this in a function to reset to dashboard
        buttonPanel.removeAll();
        buttonPanel.add(dashboard);
        buttonPanel.revalidate();
        buttonPanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String password = JOptionPane.showInputDialog("Enter SQL Password: ");
        SQLConnect.setPassword(password);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            final String url = "jdbc:mysql://localhost:3306/?allowMultiQueries=true";
            Connection conn = DriverManager.getConnection(url, "root", password);

            try {
                final String URL = "jdbc:mysql://localhost:3306/theatershows";
                Connection conn2 = DriverManager.getConnection(URL, "root", password);
                JOptionPane.showMessageDialog(null, "SUCCESSFULLY CONNECTED TO DATABASE");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error connecting to DB: " + e.getMessage(), "Database Connection Error", JOptionPane.ERROR_MESSAGE);
                System.exit(1);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Wrong Password", JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel GroupNo;
    private JButton bookTickets;
    private JButton bookingStatus;
    private JPanel buttonPanel;
    private JButton cancelBookings;
    private JButton customerRecords;
    private JLabel dashboard;
    private JButton financialPerformance;
    private JPanel header;
    private JButton payments;
    private JLabel records;
    private JLabel reports;
    private JButton scheduleShows;
    private JButton showRecords;
    private JPanel sidebar;
    private JButton staffAssignment;
    private JButton staffAssignments;
    private JButton staffRecords;
    private JButton theaterPerformance;
    private JButton theaterRecords;
    private JLabel title;
    private JLabel transaction1;
    // End of variables declaration//GEN-END:variables
}
